import LogoSrc from "../assets/icons/logo.jpeg";
// import ProjectSrc from "../assets/images/project.jpg";
// import ArchivesSrc from "../assets/images/archives.jpg";

export const data = {
  about: {
    logo: LogoSrc,
    title:
      "I'm Lubna — a frontend developer, passionate about crafting intuitive user experiences.",
    content: [
      "My journey began with a fascination for technology during my early years, which evolved into a career driven by a commitment to excellence in coding and user experience design.",
      "I have honed my skills in translating design concepts into functional web applications.",
      "My expertise spans across modern frontend technologies such as HTML5, CSS3, JavaScript, and various frameworks like React and Next JS, enabling me to create dynamic and responsive interfaces that elevate user interaction.",
    ],
  },
  education: [
    {
      id: 1,
      institution: "MSAJCE",
      course: "B.Tech IT",
      marks: "8.8 GPA",
      duration: "2019-2023",
    },
    {
      id: 2,
      institution: "Crescent",
      course: "12th Grade",
      marks: "60%",
      duration: "2018-2019",
    },
  ],
  experience: [
    {
      id: 1,
      company: "Alphabit Technologies",
      category: "IT Services and IT Consulting",
      year: "2025-Present",
    },
    {
      id: 2,
      company: "SenseGrass",
      category: "Agri-Tech",
      year: "2023-2024",
    },
    {
      id: 3,
      company: "Kuvi Network",
      category: "Ed-Tech",
      year: "2023",
    },
    {
      id: 4,
      company: "Fibo",
      category: "Health & Fitness",
      year: "2023",
    },
  ],
  footer: {
    socialLinks: [
      {
        id: 1,
        text: "Contact",
        url: "mailto:lubnafathima275@gmail.com",
      },
      {
        id: 2,
        text: "Github",
        url: "https://github.com/lubnafathima",
      },
      {
        id: 3,
        text: "LinkedIn",
        url: "https://www.linkedin.com/in/lubna-fathima-n/",
      },
      {
        id: 4,
        text: "Twitter",
        url: "https://twitter.com/MsCoder1/",
      },
    ],
    copywrite: "© 2024 Lubna Fathima N",
  },
  work: [
    {
      imgSrc: "https://github.com/user-attachments/assets/036a8f08-a774-4086-b7eb-6356e22735c2",
      demoLink: "https://sensegrass.com/",
      githubLink: "",
      title: "SenseGrass",
      description: "Next JS, React JS, Redux, Tailwind CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/5fa21ea2-c805-44e2-8170-4f1e9ae9be64",
      demoLink: "https://munafa.money/",
      githubLink: "",
      title: "Munafa",
      description: "Next JS, React JS, Redux, Tailwind CSS",
    },   
    {
      imgSrc: "https://github.com/user-attachments/assets/fe4a9983-d8df-4f28-a17d-86cac64bc816",
      demoLink: "https://connect-border-landing-page.vercel.app/",
      githubLink: "",
      title: "Connect Border",
      description: "Next JS, React JS, Tailwind CSS",
    },    
  ],
  archives: [
    {
      imgSrc: "https://github.com/user-attachments/assets/4bbc29fa-e4e2-4f83-93a7-948deba1a419",
      demoLink: "https://calendar-vite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/calendar-vite",
      title: "Calendar",
      description: "React JS, JavaScript, Vite",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/f929bf8a-99db-4676-9961-4da19940c8c1",
      demoLink: "https://react-swiggy-app.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-swiggy",
      title: "Swiggy",
      description: "React, Parcel, API",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/5a75962b-7e86-48a0-8899-e95a97995d25",
      demoLink: "https://counter-vite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/counter-vite",
      title: "Counter",
      description: "React JS, JavaScript, Vite",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/15365c35-a10b-4933-9330-77ddedb3da57",
      demoLink: "https://youtubevite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/youtube-vite",
      title: "YouTube",
      description: "React JS, JavaScript, Vite",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/32684b97-5379-492a-9077-5e11bc1bd3d2",
      demoLink: "https://calendar-cra.vercel.app/",
      githubLink: "https://github.com/lubnafathima/calendar-cra",
      title: "Calendar",
      description: "React JS | JavaScript | Create React App",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/6eb788ed-5c00-4ad9-afd1-8f76caf44935",
      demoLink: "https://website-delta4.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-website",
      title: "Website",
      description: "React, Components, Parcel",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/5cfc156c-619b-4a79-8386-0454866179e1",
      demoLink: "https://keywords-in-react.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-keywords",
      title: "Keyword",
      description: "React, Parcel",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/a8082edd-44f8-4e6e-856d-1e9433da34f0",
      demoLink: "https://calendar-react-project.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-calendar",
      title: "Calendar",
      description: "React, FullCalendar",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/c002bdc0-a501-49c8-9ad2-32aad663e874",
      demoLink: "https://react-portfolio-lubna.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-portfolio",
      title: "Portfolio",
      description: "Developed a Portfolio using React",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/57179f8f-9553-40e2-add6-f5eb89de7007",
      demoLink: "https://lubnafathima.github.io/CSS12-Messenger/",
      githubLink: "https://github.com/lubnafathima/CSS12-Messenger",
      title: "Messenger",
      description: "HTML, CSS, JS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/72105683-42db-4c63-9397-5605cb588e93",
      demoLink: "https://lubnafathima.github.io/CSS11-John_Doe/",
      githubLink: "https://github.com/lubnafathima/CSS11-John_Doe",
      title: "John Doe",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/e2b56f44-1216-4639-8abc-b8a0c33c40c7",
      demoLink: "https://lubnafathima.github.io/CSS10B-style/",
      githubLink: "https://github.com/lubnafathima/CSS10B-style",
      title: "Style",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/f1e8063d-ec37-4d39-bff0-a7a3e9cf0f10",
      demoLink: "https://lubnafathima.github.io/CSS10A-Abstract/",
      githubLink: "https://github.com/lubnafathima/CSS10A-Abstract",
      title: "Abstract",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/1b8df698-1457-4ec3-b521-f04521d27533",
      demoLink: "https://lubnafathima.github.io/CSS9B-Frontend_Practice/",
      githubLink: "https://github.com/lubnafathima/CSS9B-Frontend_Practice",
      title: "Frontend Practice",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/3a5194ca-0900-47b2-b73a-c24bebc2a84b",
      demoLink: "https://lubnafathima.github.io/CSS9-GoDaddy/",
      githubLink: "https://github.com/lubnafathima/CSS9-GoDaddy",
      title: "GoDaddy",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/f46dcb42-9849-4200-ad26-a706a1e4784d",
      demoLink: "https://github.com/lubnafathima/CSS8-Nintendo",
      githubLink: "https://github.com/lubnafathima/CSS8-Nintendo",
      title: "Nintendo",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/71384168-3cb1-4e27-8cae-b5cce8ba99f6",
      demoLink: "https://lubnafathima.github.io/CSS7B-landing/",
      githubLink: "https://github.com/lubnafathima/CSS7B-landing",
      title: "Courses",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/b48f17da-1783-4b68-9aa1-cea28ddeb925",
      demoLink: "https://lubnafathima.github.io/CSS7A-MindfulMe/",
      githubLink: "https://github.com/lubnafathima/CSS7A-MindfulMe",
      title: "MindfulMe",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/7d86dc53-eff5-4d7c-ab92-e7675ab779aa",
      demoLink: "https://lubnafathima.github.io/CSS5-landing/",
      githubLink: "https://github.com/lubnafathima/CSS5-landing",
      title: "Landing Page",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/4538768e-eeec-4a8a-aad4-5749b20fc949",
      demoLink: "https://lubnafathima.github.io/CSS4-company_website/",
      githubLink: "https://github.com/lubnafathima/CSS4-company_website",
      title: "Company",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/80cdc14d-5ccb-44c9-9e0f-2e773a0b3f14",
      demoLink: "https://lubnafathima.github.io/CSS3-design_certificate/",
      githubLink: "https://github.com/lubnafathima/CSS3-design_certificate",
      title: "Designing Certificate",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/b48d1266-549b-4857-9461-f9f82e6a5fd3",
      demoLink: "https://lubnafathima.github.io/CSS1-portfolio/",
      githubLink: "https://github.com/lubnafathima/CSS1-portfolio",
      title: "Portfolio",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/b42fadd6-4c33-4dbb-9977-03a1a144f7fc",
      demoLink: "https://lubnafathima.github.io/CSS2-certificate/",
      githubLink: "https://github.com/lubnafathima/CSS2-certificate",
      title: "Certificate",
      description: "HTML, CSS",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/145ed106-dad3-423a-a6f5-9c1cc0f579f2",
      demoLink: "https://lubnafathima.github.io/HTML5-travel_website/",
      githubLink: "https://github.com/lubnafathima/HTML5-travel_website",
      title: "Travel website",
      description: "Developed a travel website using HTML",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/c320fc48-470a-4267-9547-93a0d4748678",
      demoLink: "https://lubnafathima.github.io/HTML4-tables_-_tags/",
      githubLink: "https://github.com/lubnafathima/HTML4-tables_-_tags",
      title: "Table - Tag",
      description: "HTML",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/98483559-fe44-4a3b-abb9-be5705fae5af",
      demoLink: "https://lubnafathima.github.io/HTML3-coffee_shop/",
      githubLink: "https://github.com/lubnafathima/HTML3-coffee_shop",
      title: "Coffee Shop",
      description: "HTML",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/8730cc48-e58a-49ff-b32a-8f8d87b012af",
      demoLink: "https://lubnafathima.github.io/HTML2-tables/",
      githubLink: "https://github.com/lubnafathima/HTML2-tables",
      title: "Table",
      description: "HTML",
    },
    {
      imgSrc: "https://github.com/user-attachments/assets/3d448031-01cb-4bf0-a6b9-e1fd3310e5f5",
      demoLink: "https://lubnafathima.github.io/HTML1-portfolio/",
      githubLink: "https://github.com/lubnafathima/HTML1-portfolio",
      title: "Portfolio",
      description: "HTML",
    },
  ],
};
