import LogoSrc from "../assets/icons/logo.jpeg";
import ProjectSrc from "../assets/images/project.jpg";
import ArchivesSrc from "../assets/images/archives.jpg";

export const data = {
  about: {
    logo: LogoSrc,
    title:
      "I'm Lubna — a frontend developer, passionate about crafting intuitive user experiences.",
    content: [
      "My journey began with a fascination for technology during my early years, which evolved into a career driven by a commitment to excellence in coding and user experience design.",
      "I have honed my skills in translating design concepts into functional web applications.",
      "My expertise spans across modern frontend technologies such as HTML5, CSS3, JavaScript, and various frameworks like React and Next JS, enabling me to create dynamic and responsive interfaces that elevate user interaction.",
    ],
  },
  education: [
    {
      id: 1,
      institution: "MSAJCE",
      course: "B.Tech IT",
      marks: "8.8 GPA",
      duration: "2019-2023",
    },
    {
      id: 2,
      institution: "Crescent",
      course: "12th Grade",
      marks: "60%",
      duration: "2018-2019",
    },
  ],
  experience: [
    {
      id: 1,
      company: "SenseGrass",
      category: "Agri-Tech",
      year: "2023-2024",
    },
    {
      id: 2,
      company: "Kuvi Network",
      category: "Ed-Tech",
      year: "2023",
    },
    {
      id: 3,
      company: "Fibo",
      category: "Health & Fitness",
      year: "2023",
    },
  ],
  work: [
    {
      id: 1,
      imgSrc: ProjectSrc,
      demoLink: "https://calendar-cra.vercel.app/",
      githubLink: "https://github.com/lubnafathima/calendar-cra",
      title: "Calendar CRA",
      description: "Developed a website using React",
      designation: "Developer",
    },
    {
      id: 2,
      imgSrc: ProjectSrc,
      demoLink: "https://counter-vite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/counter-vite",
      title: "Counter",
      description: "Developed a Counter using Vite + React",
      designation: "Developer",
    },
    {
      id: 3,
      imgSrc: ProjectSrc,
      demoLink: "https://youtubevite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/youtube-vite",
      title: "YouTube",
      description: "Developed a Youtube website using Vite + React",
      designation: "Developer",
    },
  ],
  archives: [
    {
      id: 1,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/HTML1-portfolio/",
      githubLink: "https://github.com/lubnafathima/HTML1-portfolio",
      title: "Portfolio",
      description: "Developed a portfolio using HTML",
      designation: "Developer",
    },
    {
      id: 2,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/HTML2-tables/",
      githubLink: "https://github.com/lubnafathima/HTML2-tables",
      title: "Table",
      description: "Developed a table using HTML",
      designation: "Developer",
    },
    {
      id: 3,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/HTML3-coffee_shop/",
      githubLink: "https://github.com/lubnafathima/HTML3-coffee_shop",
      title: "Coffee Shop",
      description: "Developed a coffee shop website using HTML",
      designation: "Developer",
    },
    {
      id: 4,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/HTML4-tables_-_tags/",
      githubLink: "https://github.com/lubnafathima/HTML4-tables_-_tags",
      title: "Table - Tag",
      description: "Developed a table containing Tags using HTML",
      designation: "Developer",
    },
    {
      id: 5,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/HTML5-travel_website/",
      githubLink: "https://github.com/lubnafathima/HTML5-travel_website",
      title: "Travel website",
      description: "Developed a travel website using HTML",
      designation: "Developer",
    },
    {
      id: 6,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS1-portfolio/",
      githubLink: "https://github.com/lubnafathima/CSS1-portfolio",
      title: "Portfolio",
      description: "Developed a portfolio using CSS",
      designation: "Developer",
    },
    {
      id: 6,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS2-certificate/",
      githubLink: "https://github.com/lubnafathima/CSS2-certificate",
      title: "Certificate",
      description: "Developed a certificate website using CSS",
      designation: "Developer",
    },
    {
      id: 7,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS3-design_certificate/",
      githubLink: "https://github.com/lubnafathima/CSS3-design_certificate",
      title: "Designing Certificate",
      description: "Developed a designing certificate website using CSS",
      designation: "Developer",
    },
    {
      id: 8,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS4-company_website/",
      githubLink: "https://github.com/lubnafathima/CSS4-company_website",
      title: "Company",
      description: "Developed a company website using CSS",
      designation: "Developer",
    },
    {
      id: 9,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS5-landing/",
      githubLink: "https://github.com/lubnafathima/CSS5-landing",
      title: "Landing Page",
      description: "Developed a landing page using CSS",
      designation: "Developer",
    },
    {
      id: 10,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS6-position/",
      githubLink: "https://github.com/lubnafathima/CSS6-position",
      title: "Css Position",
      description: "Developed a website for CSS positioning using CSS",
      designation: "Developer",
    },
    {
      id: 11,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS7A-MindfulMe/",
      githubLink: "https://github.com/lubnafathima/CSS7A-MindfulMe",
      title: "MindfulMe",
      description: "Developed a website for MindfulMe using CSS",
      designation: "Developer",
    },
    {
      id: 12,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS7B-landing/",
      githubLink: "https://github.com/lubnafathima/CSS7B-landing",
      title: "Courses",
      description: "Developed a website for courses using CSS",
      designation: "Developer",
    },
    {
      id: 13,
      imgSrc: ArchivesSrc,
      demoLink: "https://github.com/lubnafathima/CSS8-Nintendo",
      githubLink: "https://github.com/lubnafathima/CSS8-Nintendo",
      title: "Nintendo",
      description: "Developed a Nintendo website using CSS",
      designation: "Developer",
    },
    {
      id: 14,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS9-GoDaddy/",
      githubLink: "https://github.com/lubnafathima/CSS9-GoDaddy",
      title: "GoDaddy",
      description: "Developed a website using CSS",
      designation: "Developer",
    },
    {
      id: 15,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS9B-Frontend_Practice/",
      githubLink: "https://github.com/lubnafathima/CSS9B-Frontend_Practice",
      title: "Frontend Practice",
      description: "Developed a Frontend Practice website using CSS",
      designation: "Developer",
    },
    {
      id: 16,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS10A-Abstract/",
      githubLink: "https://github.com/lubnafathima/CSS10A-Abstract",
      title: "Abstract",
      description: "Developed a abstract website using CSS",
      designation: "Developer",
    },
    {
      id: 17,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS10B-style/",
      githubLink: "https://github.com/lubnafathima/CSS10B-style",
      title: "Style",
      description: "Developed a style website using CSS",
      designation: "Developer",
    },
    {
      id: 18,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS11-John_Doe/",
      githubLink: "https://github.com/lubnafathima/CSS11-John_Doe",
      title: "John Doe",
      description: "Developed a John Doe website using CSS",
      designation: "Developer",
    },
    {
      id: 19,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/CSS12-Messenger/",
      githubLink: "https://github.com/lubnafathima/CSS12-Messenger",
      title: "Messenger",
      description: "Developed a messenger website using CSS",
      designation: "Developer",
    },
    {
      id: 20,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/JS1-alert/",
      githubLink: "https://github.com/lubnafathima/JS1-alert",
      title: "Alert",
      description: "Developed an alert using JS",
      designation: "Developer",
    },
    {
      id: 21,
      imgSrc: ArchivesSrc,
      demoLink: "https://lubnafathima.github.io/JS2-DOM_list/",
      githubLink: "https://github.com/lubnafathima/JS2-DOM_list",
      title: "DOM list",
      description: "Developed a DOM list using JS",
      designation: "Developer",
    },
    {
      id: 22,
      imgSrc: ArchivesSrc,
      demoLink: "https://react-igniting.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-igniting",
      title: "Igniting",
      description: "Developed an Igniting app using Recat",
      designation: "Developer",
    },
    {
      id: 23,
      imgSrc: ArchivesSrc,
      demoLink: "https://react-portfolio-lubna.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-portfolio",
      title: "Portfolio",
      description: "Developed a Portfolio using React",
      designation: "Developer",
    },
    {
      id: 24,
      imgSrc: ArchivesSrc,
      demoLink: "https://calendar-react-project.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-calendar",
      title: "Calendar",
      description: "Developed a calendar using React",
      designation: "Developer",
    },
    {
      id: 25,
      imgSrc: ArchivesSrc,
      demoLink: "https://keywords-in-react.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-keywords",
      title: "Keyword",
      description: "Developed a keyword website using React",
      designation: "Developer",
    },
    {
      id: 26,
      imgSrc: ArchivesSrc,
      demoLink: "https://cra-react.vercel.app/",
      githubLink: "https://github.com/lubnafathima/CRA",
      title: "Create React App",
      description: "Developed a CRA website",
      designation: "Developer",
    },
    {
      id: 27,
      imgSrc: ArchivesSrc,
      demoLink: "https://vite-react-js.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-vite",
      title: "Vite + React",
      description: "Developed a Vite + React website",
      designation: "Developer",
    },
    {
      id: 28,
      imgSrc: ArchivesSrc,
      demoLink: "https://website-delta4.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-website",
      title: "Website",
      description: "Developed a website using React",
      designation: "Developer",
    },
    {
      id: 29,
      imgSrc: ArchivesSrc,
      demoLink: "https://calendar-cra.vercel.app/",
      githubLink: "https://github.com/lubnafathima/calendar-cra",
      title: "Calendar CRA",
      description: "Developed a website using React",
      designation: "Developer",
    },
    {
      id: 30,
      imgSrc: ArchivesSrc,
      demoLink: "https://counter-vite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/counter-vite",
      title: "Counter",
      description: "Developed a Counter using Vite + React",
      designation: "Developer",
    },
    {
      id: 31,
      imgSrc: ArchivesSrc,
      demoLink: "https://react-swiggy-app.vercel.app/",
      githubLink: "https://github.com/lubnafathima/react-swiggy",
      title: "Swiggy",
      description: "Developed a Swiggy Website using React",
      designation: "Developer",
    },
    {
      id: 32,
      imgSrc: ArchivesSrc,
      demoLink: "https://youtubevite.vercel.app/",
      githubLink: "https://github.com/lubnafathima/youtube-vite",
      title: "YouTube",
      description: "Developed a Youtube website using Vite + React",
      designation: "Developer",
    },
  ],
  footer: {
    socialLinks: [
      {
        id: 1,
        text: "Contact",
        url: "mailto:lubnafathima275@gmail.com",
      },
      {
        id: 2,
        text: "Github",
        url: "https://github.com/lubnafathima",
      },
      {
        id: 3,
        text: "LinkedIn",
        url: "https://www.linkedin.com/in/lubna-fathima-n/",
      },
      {
        id: 4,
        text: "Twitter",
        url: "https://twitter.com/MsCoder1/",
      },
    ],
    copywrite: "© 2024 Lubna Fathima N",
  },
};
